
version: '3'


services:
  web:
    build:
      context: ./task-client/
      dockerfile: Dockerfile
    ports:
      - '${PORT_WEB}:80'
    restart: always  

  gateway:
    build:
      context: ./gateway-nginx/
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    volumes:
      - ./gateway-nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env 
    restart: always

  auth:
    build:
      context: ./Auth-Microservice/
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - mongo  
    env_file:
      - .env  
    restart: always

  task:
    build:
      context: ./Task-Microservice/
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    env_file:
      - .env 
    restart: always

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./Mongo-Data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
    restart: always

