
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjA2MTA4ZDNjODEyNjA4ZjQ2MzI2YyIsImlhdCI6MTY4NDA0NzQ0NywiZXhwIjoxNjg0MDUxMDQ3fQ.95r52kyC5mELiPT6ylTuYWBRGb9pxOQfZkFrwilfHIY
POST http://localhost:3001/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@essxample.com",
    "password": "password123"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@essxample.com",
    "password": "password123"
}

###
GET http://localhost:3000/api/auth/profile/64613e9bacad998222281092 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST http://localhost:3000/api/task
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Nueva tarea",
    "description": "Descripción de la nueva tarea"
}

###
PUT http://localhost:3000/api/task/64613ec5a646d367b81e4cc4
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Tarea actualizadass",
    "description": "Descripción sssss"
}

###
PUT http://localhost:3000/api/task/complete/646077e04c75373a06e02bbf HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "done": true
}

###
GET http://localhost:3000/api/task/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
GET http://localhost:3000/api/task/64613ec5a646d367b81e4cc4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/api/task/646077f24c75373a06e02bc3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}